PREVIEW_COLUMN_SECS = 2

PREVIEW_MARGIN_Y = 0.1
PREVIEW_MARGIN_X = 0.25
PREVIEW_TEXT_MARGIN_X = 0.015
PREVIEW_TEXT_MARGIN_Y = 0
PREVIEW_TEXT_HEIGHT = 0.12
PREVIEW_TEXT_WIDTH = PREVIEW_MARGIN_X - 2 * PREVIEW_TEXT_MARGIN_X

PREVIEW_LANE_WIDTH = 0.072
PREVIEW_STAGE_BORDER_WIDTH = 0.25 * PREVIEW_LANE_WIDTH
PREVIEW_NOTE_WIDTH = PREVIEW_LANE_WIDTH
PREVIEW_BAR_LINE_HEIGHT = 0.0036
PREVIEW_BAR_LINE_ALPHA = 0.8

PREVIEW_COVER_ALPHA = 1.0

PREVIEW_Y_MIN = -1 + PREVIEW_MARGIN_Y
PREVIEW_Y_MAX = 1 - PREVIEW_MARGIN_Y

PREVIEW_BAR_EXTEND_WIDTH = 3 * PREVIEW_LANE_WIDTH

PREVIEW_FLICK_ARROW_Y_OFFSET = 0.9 * PREVIEW_NOTE_WIDTH
