from sonolus.script.bucket import Bucket, bucket, bucket_sprite, buckets
from sonolus.script.text import StandardText

from sekai.lib.skin import Skin


@buckets
class Buckets:
    normal_tap_note: Bucket = bucket(
        sprites=[
            bucket_sprite(
                sprite=Skin.normal_note_fallback,
                x=0,
                y=0,
                w=2,
                h=2,
                rotation=-90,
            )
        ],
        unit=StandardText.MILLISECOND_UNIT,
    )
    normal_flick_note: Bucket = bucket(
        sprites=[
            bucket_sprite(
                sprite=Skin.flick_note_fallback,
                x=0,
                y=0,
                w=2,
                h=2,
                rotation=-90,
            ),
            bucket_sprite(
                sprite=Skin.flick_arrow_fallback,
                x=1,
                y=0,
                w=2,
                h=2,
                rotation=-90,
            ),
        ],
        unit=StandardText.MILLISECOND_UNIT,
    )
    normal_slide_start_note: Bucket = bucket(
        sprites=[
            bucket_sprite(
                sprite=Skin.normal_slide_connector_fallback,
                x=0.5,
                y=0,
                w=2,
                h=5,
                rotation=-90,
            ),
            bucket_sprite(
                sprite=Skin.slide_note_fallback,
                x=-2,
                y=0,
                w=2,
                h=2,
                rotation=-90,
            ),
        ],
        unit=StandardText.MILLISECOND_UNIT,
    )
    normal_slide_end_note: Bucket = bucket(
        sprites=[
            bucket_sprite(
                sprite=Skin.normal_slide_connector_fallback,
                x=-0.5,
                y=0,
                w=2,
                h=5,
                rotation=-90,
            ),
            bucket_sprite(
                sprite=Skin.slide_note_end_fallback,
                x=2,
                y=0,
                w=2,
                h=2,
                rotation=-90,
            ),
        ],
        unit=StandardText.MILLISECOND_UNIT,
    )
    normal_slide_end_flick_note: Bucket = bucket(
        sprites=[
            bucket_sprite(
                sprite=Skin.normal_slide_connector_fallback,
                x=-0.5,
                y=0,
                w=2,
                h=5,
                rotation=-90,
            ),
            bucket_sprite(
                sprite=Skin.flick_note_fallback,
                x=2,
                y=0,
                w=2,
                h=2,
                rotation=-90,
            ),
            bucket_sprite(
                sprite=Skin.flick_arrow_fallback,
                x=3,
                y=0,
                w=2,
                h=2,
                rotation=-90,
            ),
        ],
        unit=StandardText.MILLISECOND_UNIT,
    )
    critical_tap_note: Bucket = bucket(
        sprites=[
            bucket_sprite(
                sprite=Skin.critical_note_fallback,
                x=0,
                y=0,
                w=2,
                h=2,
                rotation=-90,
            )
        ],
        unit=StandardText.MILLISECOND_UNIT,
    )
    critical_flick_note: Bucket = bucket(
        sprites=[
            bucket_sprite(
                sprite=Skin.critical_note_fallback,
                x=0,
                y=0,
                w=2,
                h=2,
                rotation=-90,
            ),
            bucket_sprite(
                sprite=Skin.critical_arrow_fallback,
                x=1,
                y=0,
                w=2,
                h=2,
                rotation=-90,
            ),
        ],
        unit=StandardText.MILLISECOND_UNIT,
    )
    critical_slide_start_note: Bucket = bucket(
        sprites=[
            bucket_sprite(
                sprite=Skin.critical_slide_connector_fallback,
                x=0.5,
                y=0,
                w=2,
                h=5,
                rotation=-90,
            ),
            bucket_sprite(
                sprite=Skin.critical_note_fallback,
                x=-2,
                y=0,
                w=2,
                h=2,
                rotation=-90,
            ),
        ],
        unit=StandardText.MILLISECOND_UNIT,
    )

    critical_slide_end_note: Bucket = bucket(
        sprites=[
            bucket_sprite(
                sprite=Skin.critical_slide_connector_fallback,
                x=-0.5,
                y=0,
                w=2,
                h=5,
                rotation=-90,
            ),
            bucket_sprite(
                sprite=Skin.critical_note_end_fallback,
                x=2,
                y=0,
                w=2,
                h=2,
                rotation=-90,
            ),
        ],
        unit=StandardText.MILLISECOND_UNIT,
    )
    critical_slide_end_flick_note: Bucket = bucket(
        sprites=[
            bucket_sprite(
                sprite=Skin.critical_slide_connector_fallback,
                x=-0.5,
                y=0,
                w=2,
                h=5,
                rotation=-90,
            ),
            bucket_sprite(
                sprite=Skin.critical_note_end_fallback,
                x=2,
                y=0,
                w=2,
                h=2,
                rotation=-90,
            ),
            bucket_sprite(
                sprite=Skin.critical_arrow_fallback,
                x=3,
                y=0,
                w=2,
                h=2,
                rotation=-90,
            ),
        ],
        unit=StandardText.MILLISECOND_UNIT,
    )
    normal_trace_note: Bucket = bucket(
        sprites=[
            bucket_sprite(
                sprite=Skin.normal_note_fallback,
                x=0,
                y=0,
                w=2,
                h=2,
                rotation=-90,
            )
        ],
        unit=StandardText.MILLISECOND_UNIT,
    )
