LAYER_BACKGROUND_COVER = -1
LAYER_STAGE = 0
LAYER_COVER = 1
LAYER_JUDGMENT_LINE = 2

LAYER_SLOT_EFFECT = 10

LAYER_SIM_LINE = 20
LAYER_NOTE_CONNECTOR_CRITICAL = 21
LAYER_NOTE_CONNECTOR_NORMAL = 22
LAYER_NOTE_GUIDE = 23
LAYER_NOTE_SLIDE = 24
LAYER_NOTE_SLIM_BODY = 25
LAYER_NOTE_BODY = 26
LAYER_NOTE_TICK = 27
LAYER_NOTE_ARROW = 28

LAYER_SLOT_GLOW_EFFECT = 30


def get_z(layer: int, time: float = 0.0, lane: float = 0.0, etc: int | float = 0.0) -> float:
    return (1 / 128) * etc - (1 / 128) * lane - time + 512 * layer
