LAYER_BACKGROUND_COVER = -1
LAYER_STAGE = 0
LAYER_COVER = 1
LAYER_JUDGMENT_LINE = 2
LAYER_SLOT_EFFECT = 3

LAYER_PREVIEW_COVER = 10
LAYER_BEAT_LINE = 11
LAYER_SIM_LINE = 12
LAYER_TIME_LINE = 13
LAYER_BPM_LINE = 14
LAYER_TIMESCALE_LINE = 15

LAYER_ACTIVE_SIDE_CONNECTOR = 20
LAYER_NOTE_GUIDE = 21
LAYER_NOTE_SLIM_BODY = 22
LAYER_NOTE_FLICK_BODY = 23
LAYER_NOTE_BODY = 24
LAYER_NOTE_TICK = 25
LAYER_NOTE_ARROW = 26
LAYER_SLOT_GLOW_EFFECT = 27


def get_z(layer: int, time: float = 0.0, lane: float = 0.0, etc: int | float = 0.0) -> float:
    return (1 / 128) * etc + (1 / 128) * abs(lane) - time + 512 * layer
